name: network_monitor_ios
description: "iOS Network Monitor App"

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.1
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.0.0
  http: ^1.1.0
  provider: ^6.1.1
  background_fetch: ^1.1.0   
  workmanager: ^0.5.1        

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true