name: network_monitor_ios
description: "iOS Network Monitor with Background"

publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'  # Sửa xuống cho tương thích

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.2    # Giảm xuống
  flutter_local_notifications: ^13.0.0  # Giảm xuống
  permission_handler: ^10.4.2  # Giảm xuống
  http: ^0.13.5               # Giảm xuống
  background_fetch: ^1.0.1    # Giảm xuống
  workmanager: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true